# Generated by Django 5.2.11 on 2026-03-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('IT', 'IT'), ('CS', 'Computer Science'), ('DS', 'Data Science'), ('HR', 'HR'), ('Python Developer', 'Python Developer'), ('Java Developer', 'Java Developer')], max_length=50),
        ),
    ]
